---
abstract: "Check to see that version's in modules are sane"
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.94
  Test::Requires: 0
  Test::Tester: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Version
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
requires:
  Carp: 0
  Exporter: 0
  File::Find::Rule::Perl: 0
  Module::Metadata: 0
  Test::Builder: 0
  Test::More: 0
  parent: 0
  perl: 5.006
  strict: 0
  version: 0.86
  warnings: 0
resources:
  bugtracker: https://github.com/gitpan/Test-Version/issues
  homepage: http://search.cpan.org/dist/Test-Version/
  repository: git://github.com/gitpan/Test-Version.git
version: 1.002000
