---
abstract: "Check to see that version's in modules are sane"
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Mike Doherty <doherty@cs.dal.ca>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Builder::Tester: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Version
no_index:
  directory:
    - corpus
  file:
    - perlcritic.rc
requires:
  Exporter: 0
  File::Find::Rule::Perl: 0
  Module::Extract::VERSION: 0
  Test::Builder: 0
  Test::More: 0
  boolean: 0
  parent: 0
  perl: 5.006
  version: 0.77
resources:
  bugtracker: http://github.com/xenoterracide/Test-Version/issues
  repository: git://github.com/xenoterracide/Test-Version.git
version: 0.04
